SKILL_KEYWORDS = [
    "Python",
    "FastAPI",
    "FAISS",
    "Kubernetes",
    "Docker",
    "AWS",
    "GCP",
    "Azure",
    "Postgres",
    "Redis",
    "Terraform",
    "Next.js",
    "React",
    "TypeScript",
    "Recharts",
    "Sentence Transformers",
    "spaCy",
    "Cross-Encoders",
    "NLP",
    "CI/CD",
]
